import { ArrowDownRight, ArrowRight, Check, Compass, Layers3, Play, Search, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import SiteNav from "@/components/SiteNav";
import { trpc } from "@/lib/trpc";

function ProductCard({ entry, index }: { entry: any; index: number }) {
  const product = entry.product;
  const categoryName = entry.category?.name ?? product.category;
  return <article className="product-card glass overflow-hidden rounded-[28px] border border-white/10"><Link href={`/websites/${product.slug}`} className="block"><div className="relative aspect-[16/10] overflow-hidden bg-[#081a2d]"><img src={product.heroImage} alt={`${product.name} website preview`} className="h-full w-full object-cover opacity-90" loading="lazy" /><div className="absolute inset-0 bg-gradient-to-t from-[#06111f] via-transparent to-transparent opacity-70" /><div className="absolute left-5 top-5 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.2em] text-white/70"><span className="h-2 w-2 rounded-full bg-[#52a7ff] shadow-[0_0_14px_#52a7ff]" /> 0{index + 1} / digital product</div><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between"><span className="rounded-full border border-white/15 bg-[#06111f]/65 px-3 py-1.5 text-[10px] uppercase tracking-[0.14em] text-white/75 backdrop-blur">{categoryName}</span><span className="font-mono text-xs text-white/65">{product.currency} {Number(product.price).toLocaleString("en-US")}</span></div></div><div className="space-y-5 p-6 md:p-7"><div><h3 className="text-2xl font-semibold tracking-[-0.04em] text-white">{product.name}</h3><p className="mt-2 max-w-[28rem] text-sm leading-6 text-white/55">{product.tagline}</p></div><div className="flex flex-wrap gap-2">{(entry.techStack ?? []).slice(0, 4).map((stack: any) => <span key={stack.name} className="rounded-full bg-white/[0.06] px-2.5 py-1 font-mono text-[10px] text-white/55">{stack.name}</span>)}</div><div className="flex items-center justify-between pt-1"><span className="group/link flex items-center gap-2 text-sm font-semibold text-white transition-colors hover:text-[#83c2ff]">Inspect system <ArrowRight size={16} /></span><span className="font-mono text-[10px] uppercase tracking-[0.16em] text-white/35">ready to own</span></div></div></Link></article>;
}

function readFilters() { const params = new URLSearchParams(window.location.search); return { search: params.get("search") ?? "", category: params.get("category") ?? "all" }; }

export default function Home() {
  const [filters, setFilters] = useState(readFilters);
  useEffect(() => { let frame = 0; const syncScroll = () => { cancelAnimationFrame(frame); frame = requestAnimationFrame(() => document.documentElement.style.setProperty("--numi-scroll", `${window.scrollY}px`)); }; syncScroll(); window.addEventListener("scroll", syncScroll, { passive: true }); return () => { cancelAnimationFrame(frame); window.removeEventListener("scroll", syncScroll); }; }, []);
  const categoriesQuery = trpc.marketplace.categories.useQuery();
  const queryInput = useMemo(() => ({ search: filters.search || undefined, category: filters.category }), [filters.search, filters.category]);
  const productsQuery = trpc.marketplace.list.useQuery(queryInput);
  useEffect(() => { const onPopState = () => setFilters(readFilters()); window.addEventListener("popstate", onPopState); return () => window.removeEventListener("popstate", onPopState); }, []);
  const updateFilters = (next: Partial<typeof filters>) => { const value = { ...filters, ...next }; setFilters(value); const params = new URLSearchParams(); if (value.search) params.set("search", value.search); if (value.category !== "all") params.set("category", value.category); const query = params.toString(); window.history.replaceState({}, "", `${window.location.pathname}${query ? `?${query}` : ""}#collection`); };
  const products = productsQuery.data ?? [];
  return <div className="numi-shell min-h-screen bg-[#06111f]"><div className="numi-content">
    <section className="cinematic-hero relative min-h-[760px] overflow-hidden md:min-h-[920px]"><div className="cosmic-backdrop absolute inset-0" /><img src="/assets/numi-cosmic-nebula.svg" alt="Deep space nebula" aria-hidden="true" className="cosmic-nebula absolute inset-0 h-full w-full object-cover" /><img src="/assets/numi-cosmic-hero.svg" alt="NUMI digital universe" className="cosmic-hero-image absolute inset-0 h-full w-full object-cover" /><div className="starfield starfield-a absolute inset-0" /><div className="starfield starfield-b absolute inset-0" /><div className="cosmic-vignette absolute inset-0" /><div className="cosmic-scanline absolute inset-0" /><SiteNav /><div className="relative z-10 mx-auto flex min-h-[760px] w-full max-w-[1440px] items-end px-5 pb-28 pt-24 md:min-h-[920px] md:px-10 md:pb-36"><div className="max-w-3xl"><div className="reveal mb-7 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.27em] text-[#b9d9ff]"><span className="h-px w-10 bg-[#83c2ff]" /> Built in Algeria / designed for the world</div><div className="reveal reveal-delay-1 mb-5 font-mono text-[10px] uppercase tracking-[.32em] text-white/40">Space / digital architecture / NUMI</div><h1 className="reveal reveal-delay-1 text-balance text-[clamp(3.8rem,9vw,8.5rem)] font-extrabold leading-[.88] tracking-[-0.09em] text-white">Websites<br /><span className="hero-gradient-text">built</span> to launch.</h1><p className="reveal reveal-delay-2 mt-8 max-w-xl text-lg leading-8 text-white/65 md:text-xl">Enter a cinematic digital universe for finished website systems — designed, documented, and ready for their next owner.</p><div className="reveal reveal-delay-3 mt-10 flex flex-wrap items-center gap-4"><a href="#collection" className="group flex items-center gap-3 rounded-full bg-white px-6 py-3.5 text-sm font-bold text-[#06111f] transition-transform hover:-translate-y-0.5 active:scale-[.98]">Explore the universe <ArrowDownRight size={16} /></a><a href="#showreel" className="flex items-center gap-2 rounded-full border border-white/25 px-5 py-3.5 text-sm font-semibold text-white/85 transition-colors hover:border-white/60 hover:bg-white/10"><Play size={15} fill="currentColor" /> View live demos</a></div><div className="mt-12 flex items-center gap-6 font-mono text-[9px] uppercase tracking-[.22em] text-white/35"><span>37.00°N / 3.05°E</span><span className="h-px w-12 bg-white/20" /><span>Signal detected / 01</span></div></div></div><a href="#journey" className="absolute bottom-7 left-5 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[.22em] text-white/50 transition-colors hover:text-white md:left-10"><span className="grid h-8 w-8 place-items-center rounded-full border border-white/20"><ArrowDownRight size={14} /></span> Enter the digital universe</a></section>
    <section id="journey" className="universe-journey relative overflow-hidden border-y border-white/10"><div className="journey-nebula absolute inset-0" /><div className="relative mx-auto max-w-[1440px] px-5 py-28 md:px-10 md:py-40"><div className="mb-16 max-w-3xl"><div className="mb-5 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[.26em] text-[#ef8b65]"><span>01</span><span className="h-px w-10 bg-[#ef8b65]" /> The transmission</div><h2 className="text-balance text-5xl font-semibold tracking-[-.07em] text-white md:text-7xl">From deep space<br /><span className="text-white/35">to digital ownership.</span></h2><p className="mt-6 max-w-xl text-base leading-8 text-white/50">A short visual journey through the NUMI universe: signal, structure, system, handover.</p></div><div className="journey-rail grid gap-4 md:grid-cols-4">{[["01", "SIGNAL", "A distant light", "Ideas begin as a point of energy in the dark."],["02", "STRUCTURE", "Digital architecture", "Navigation, rhythm, and interface become a system."],["03", "SYSTEM", "A world to enter", "The website is experienced, not merely displayed."],["04", "HANDOVER", "Ready to own", "Source, license, and delivery stay visible."]].map(([n, label, title, copy]) => <div key={n} className="journey-node glass rounded-3xl p-6"><div className="font-mono text-[10px] text-[#83c2ff]">{n} / {label}</div><div className="mt-14 text-2xl font-semibold text-white">{title}</div><p className="mt-3 text-sm leading-6 text-white/45">{copy}</p></div>)}</div></div></section>
    <section id="collection" className="mx-auto max-w-[1440px] px-5 py-28 md:px-10 md:py-40"><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-5 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[.26em] text-[#83c2ff]"><span>02</span><span className="h-px w-10 bg-[#83c2ff]" /> Digital showroom</div><h2 className="max-w-2xl text-balance text-5xl font-semibold tracking-[-.07em] text-white md:text-7xl">Find the system<br /><span className="text-white/35">that fits your next move.</span></h2></div><p className="max-w-sm text-sm leading-7 text-white/50">Search the real catalog by name, category, description, or technology. Every published result is served from the database.</p></div>
      <div className="arch-search glass relative overflow-hidden rounded-[28px] p-5 md:p-7"><div className="relative"><div className="font-mono text-[10px] uppercase tracking-[.24em] text-[#ef8b65]">What are you looking for?</div><div className="mt-4 flex flex-col gap-3 md:flex-row"><label className="flex flex-1 items-center gap-3 rounded-2xl border border-white/10 bg-[#06111f]/65 px-4 py-3 text-white/50"><Search size={18} /><input value={filters.search} onChange={(event) => updateFilters({ search: event.target.value })} placeholder="Search products, use cases, technologies…" className="w-full bg-transparent text-sm text-white outline-none placeholder:text-white/30" /></label>{(filters.search || filters.category !== "all") && <button type="button" onClick={() => updateFilters({ search: "", category: "all" })} className="flex items-center justify-center gap-2 rounded-2xl border border-white/15 px-5 py-3 text-xs text-white/60 hover:border-white/35 hover:text-white">Reset showroom</button>}</div><div className="mt-4 flex gap-2 overflow-x-auto pb-1" aria-label="Product categories"><button type="button" onClick={() => updateFilters({ category: "all" })} className={`shrink-0 rounded-full border px-4 py-2 text-xs transition-colors ${filters.category === "all" ? "border-[#83c2ff]/60 bg-[#83c2ff]/10 text-white" : "border-white/10 text-white/45 hover:text-white"}`}>All</button>{categoriesQuery.data?.map((category) => <button key={category.id} type="button" onClick={() => updateFilters({ category: category.slug })} className={`shrink-0 rounded-full border px-4 py-2 text-xs transition-colors ${filters.category === category.slug ? "border-[#83c2ff]/60 bg-[#83c2ff]/10 text-white" : "border-white/10 text-white/45 hover:text-white"}`}>{category.name}</button>)}</div></div></div>
      <div className="mt-8 flex items-center justify-between font-mono text-[10px] uppercase tracking-[.18em] text-white/35"><span>{filters.search || filters.category !== "all" ? `${products.length} matching systems` : "Published systems"}</span>{productsQuery.isFetching && <span className="text-[#83c2ff]">Updating showroom…</span>}</div>
      <div className="mt-5">{productsQuery.isLoading ? <div className="grid gap-6 md:grid-cols-3"><div className="shimmer h-[440px] rounded-[28px] bg-white/5" /><div className="shimmer h-[440px] rounded-[28px] bg-white/5" /><div className="shimmer h-[440px] rounded-[28px] bg-white/5" /></div> : productsQuery.isError ? <div className="glass rounded-[28px] border-red-400/20 p-10 text-center"><h3 className="text-xl font-semibold text-white">The showroom is temporarily unavailable.</h3><p className="mt-3 text-sm text-white/45">Refresh to reconnect to the catalog database.</p><button type="button" onClick={() => productsQuery.refetch()} className="mt-6 text-sm text-[#83c2ff]">Try again</button></div> : products.length ? <div className="grid gap-6 md:grid-cols-3">{products.map((entry, index) => <ProductCard key={entry.product.id} entry={entry} index={index} />)}</div> : <div className="glass rounded-[28px] border-dashed p-10 text-center"><h3 className="text-xl font-semibold text-white">No systems match this signal.</h3><p className="mt-3 text-sm text-white/45">Try another keyword or clear the category filter.</p><button type="button" onClick={() => updateFilters({ search: "", category: "all" })} className="mt-6 text-sm text-[#83c2ff]">Reset showroom</button></div>}</div>
    </section>
    <section id="principles" className="border-y border-white/10 bg-[#0a1b2d]/55"><div className="mx-auto grid max-w-[1440px] gap-14 px-5 py-28 md:grid-cols-[.8fr_1.2fr] md:px-10 md:py-36"><div><div className="mb-5 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[.26em] text-[#ef8b65]"><span>03</span><span className="h-px w-10 bg-[#ef8b65]" /> Algeria → digital</div><h2 className="max-w-xl text-balance text-5xl font-semibold tracking-[-.07em] text-white md:text-7xl">Architecture<br /><span className="text-[#ef8b65]">with a handover.</span></h2></div><div className="grid gap-5 md:grid-cols-3"><div className="glass rounded-3xl p-6"><Compass className="mb-10 text-[#83c2ff]" size={24} /><h3 className="text-lg font-semibold text-white">01 / Discover</h3><p className="mt-4 text-sm leading-6 text-white/50">A showroom language inspired by North African geometry, Mediterranean light, and modern digital craft.</p></div><div className="glass rounded-3xl p-6"><Layers3 className="mb-10 text-[#83c2ff]" size={24} /><h3 className="text-lg font-semibold text-white">02 / Choose</h3><p className="mt-4 text-sm leading-6 text-white/50">Pick a finished foundation with the source, requirements, and license made clear.</p></div><div className="glass rounded-3xl p-6"><Sparkles className="mb-10 text-[#ef8b65]" size={24} /><h3 className="text-lg font-semibold text-white">03 / Launch</h3><p className="mt-4 text-sm leading-6 text-white/50">Payment is verified server-side. Delivery records unlock only after the handover is ready.</p></div></div></div></section>
    <section id="showreel" className="mx-auto max-w-[1440px] px-5 py-28 md:px-10 md:py-36"><div className="glass relative overflow-hidden rounded-[36px] p-8 md:p-16"><div className="pattern-star absolute right-10 top-10 h-32 w-32 opacity-30" /><div className="relative max-w-3xl"><Sparkles className="mb-8 text-[#ef8b65]" size={26} /><h2 className="text-balance text-4xl font-semibold tracking-[-.06em] text-white md:text-6xl">A quieter way to buy digital work.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-white/55">No endless template scroll. No hidden license language. NUMI keeps the catalog small, the details visible, and the path from “this feels right” to “it is mine” unambiguous.</p><div className="mt-10 flex flex-wrap gap-5 font-mono text-[10px] uppercase tracking-[.18em] text-white/45"><span className="flex items-center gap-2"><Check size={14} className="text-[#83c2ff]" /> Source included</span><span className="flex items-center gap-2"><Check size={14} className="text-[#83c2ff]" /> Independent instance</span><span className="flex items-center gap-2"><Check size={14} className="text-[#83c2ff]" /> Clear license</span></div></div></div></section>
    <footer id="handover" className="border-t border-white/10"><div className="mx-auto flex max-w-[1440px] flex-col gap-6 px-5 py-10 md:flex-row md:items-center md:justify-between md:px-10"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full border border-white/25 text-sm font-bold">N</span><span className="font-mono text-sm tracking-[.3em] text-white/80">NUMI</span></div><p className="max-w-md text-xs leading-5 text-white/35">A cinematic digital showroom. Built in Algeria, designed for the world.</p><Link href="/account" className="flex items-center gap-2 text-xs text-white/50 transition-colors hover:text-white">Customer access <ArrowRight size={14} /></Link></div></footer>
  </div></div>;
}
